    <meta name="referrer" content="no-referrer-when-downgrade">
    <meta name="robots" content="all">
    <meta content="{{config('settings.social_facebook')}}" property="fb:profile_id">
    <meta content="en_US" property="og:locale">
    <meta content="{{config('settings.site_name')}}" property="og:site_name">
    <meta content="website" property="og:type">
    <meta content="{{url()->current()??config('app.url')}}" property="og:url">
    <meta content="{{$pageTitle??config('settings.site_title')}}" property="og:title">
    <meta content="{{$pageDescription??config('settings.seo_meta_description')}}" property="og:description">
    <meta content="{{asset('storage/'.config('settings.site_logo'))}}" property="og:image">
    <meta content="239" property="og:image:width">
    <meta content="41" property="og:image:height">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="@bhimrazy">
    <meta name="twitter:creator" content="@bhimrazy">
    <meta name="twitter:title" content="{{$pageTitle??config('settings.site_title')}}">
    <meta name="twitter:description" content="{{$pageDescription??config('settings.site_description')}}">
    <meta name="twitter:image" content="{{asset('storage/'.config('settings.site_logo'))}}">
    <meta name="twitter:image:width" content="239">
    <meta name="twitter:image:height" content="41">
    {{--<meta name="google-site-verification" content="">--}}
    <link href="{{url()->current()??config('app.url')}}" rel="canonical">
    <link href="{{config('app.url')}}" rel="home">
    {{--<link type="text/plain" href="https://moz.com/humans.txt" rel="author">--}}
